server:
  port: 23102

spring:
  application:
    name: rabbit-consumer
  rabbitmq:
    host: 192.168.114.167
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  cloud:
    stream:
      bindings:
        input:
          group: ams
          destination: demoExchange
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: ams