server:
  port: 23101

spring:
  application:
    name: rabbit-producer
  rabbitmq:
    host: 192.168.114.167
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  cloud:
    stream:
      bindings:
        dynamic1-channel:
          group: producer
          destination: demoExchange1
        dynamic2-channel:
          group: producer
          destination: demoExchange2
